# Generated by Django 5.1.3 on 2024-12-10 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=100, unique=True)),
                ('tentativas', models.PositiveIntegerField()),
                ('tempo', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tentativas', 'tempo', '-data_hora'],
            },
        ),
    ]
